domaframework/doma

docs/sources/release-notes.rst

ドキュメントのビルド時に次の警告が出る箇所がありました。
> WARNING: Title underline too short.
この警告を解消するため該当する見出しのアンダーラインを十分な長さにしました。

見出しのアンダーラインを十分な長さにしました。

---

src/test/java/org/seasar/doma/jdbc/CallerCommenterTest.java

String.format("%n") は、環境によって改行文字が変わります。
Windows 環境の場合、"\n" では無く "\r\n" になりテストが失敗してしまいます。
ですので System#lineSeparator を使うように修正しました。

Windows環境でテストが失敗する問題を修正

---

src/main/java/org/seasar/doma/internal/util/StringUtil.java
src/test/java/org/seasar/doma/internal/util/StringUtilTest.java

以下のパターンでは、「img1_file」となる事を期待しているが、「img1file」となる。
```
String img1File;
```
下記が 「false」となるため、うまく変換できていないようです。
```
Character.isLowerCase('1')
```
Columnアノテーションのname指定で逃げれるので現状は問題ありません。

StringUtilのfromCamelCaseToSnakeCaseで、カラム名に数字が含まれている場合意図している結果にならない

---

src/main/java/org/seasar/doma/internal/apt/EntityTypeGenerator.java
src/test/java/example/entity/ImmutableEmp.java
src/test/java/example/entity/_ImmutableEmp.java
src/test/java/org/seasar/doma/jdbc/entity/EntityTypeTest.java
src/test/resources/org/seasar/doma/internal/apt/entity/EntityProcessorTest_ImmutableChildEntity.txt
src/test/resources/org/seasar/doma/internal/apt/entity/EntityProcessorTest_ImmutableEntity.txt

エンティティフィールドに対応するカラムが SELECT 句に存在しない場合に発生していました

イミュータブルなエンティティの取得でNullPointerException が発生するバグを修正しました fix #63

---

src/main/java/org/seasar/doma/jdbc/dialect/Dialect.java
src/main/java/org/seasar/doma/jdbc/dialect/H212126Dialect.java
src/main/java/org/seasar/doma/jdbc/dialect/HsqldbDialect.java
src/main/java/org/seasar/doma/jdbc/dialect/PostgresDialect.java
src/main/java/org/seasar/doma/jdbc/dialect/SqliteDialect.java
src/main/java/org/seasar/doma/jdbc/dialect/StandardDialect.java
src/main/java/org/seasar/doma/jdbc/id/BuiltinIdentityIdGenerator.java
src/main/java/org/seasar/doma/jdbc/id/IdGenerationConfig.java
src/test/java/example/entity/IdGeneratedEmp.java
src/test/java/example/entity/_IdGeneratedEmp.java
src/test/java/org/seasar/doma/jdbc/dialect/PostgresDialectTest.java
src/test/java/org/seasar/doma/jdbc/id/BuiltinIdentityIdGeneratorTest.java
src/test/java/org/seasar/doma/jdbc/id/BuiltinSequenceIdGeneratorTest.java
src/test/java/org/seasar/doma/jdbc/id/BuiltinTableIdGeneratorTest.java

`Dialect#getIdentitySelectSql` のシグニチャを変更し、引用符で囲む前の名前を受け取るようにしました。
`PostgresDialect` の実装では、 `@Table(quote = true)` の場合、シーケンス名を作成した後で、カタログ名、スキーマ名、シーケンス名をそれぞれ引用符で囲み連結します。
```java
@Table(catalog = "catalog_name", schema = "schema_name",  name = "table_name", quote = true)
public class TableName {
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
@Column(name = "id")
Long id;
}
```
上記のエンティティクラスに対応するID取得のSQLは次のようになります。
```sql
select currval('"catalog_name"."schema_name"."table_name_id_seq"');
```
fixed #73

PostgresDialectでID生成エラーが発生する問題を修正

---

src/main/java/org/seasar/doma/jdbc/query/SqlFileDeleteQuery.java
src/main/java/org/seasar/doma/jdbc/query/SqlFileInsertQuery.java
src/main/java/org/seasar/doma/jdbc/query/SqlFileUpdateQuery.java
src/test/java/org/seasar/doma/jdbc/query/SqlFileUpdateQueryTest.java
src/test/resources/META-INF/org/seasar/doma/jdbc/query/SqlFileUpdateQueryTest/testNonEntity.sql

以下のような、Daoメソッドの一番目のパラメータが非エンティティクラスの場合にのみ発生する不具合でした。
```java
@Update(sqlFile = true)
int update(String name);
```

SQLファイルを使った更新がスキップされる問題を修正 fix #78

---

src/main/java/org/seasar/doma/jdbc/type/JdbcTypes.java
src/main/java/org/seasar/doma/jdbc/type/PortableObjectType.java

最大限のポータビリティを得るには `setObject(int parameterIndex, Object x)` よりも `setObject(int parameterIndex, Object x, int sqlType)` を使うべきという記述が `java.sql. PreparedStatement ` のJavaDocコメントにあります。実際に、PostgreSQLにおいては、 `setObject(int parameterIndex, Object x, int sqlType)` を使うことでPostgreSQL独自のjson型やdaterange型を標準JDBC APIで扱えます。
この修正では、Dialectの生成時に定型的なコードを記述することで、ポータビリティの高い `PreparedStatement#setObject` を利用可能にします。
利用例は以下の通りです。
```java
PostgresDialect dialect = new PostgresDialect(new PostgresJdbcMappingVisitor() {
@Override
public Void visitObjectWrapper(ObjectWrapper wrapper,
JdbcMappingFunction p, JdbcMappingHint q)
throws SQLException {
return p.apply(wrapper, JdbcTypes.PORTABLE_OBJECT);
}
});
```
`visitObjectWrapper` メソッドの第3パラメータ `JdbcMappingHint ` …

ポータビリティの高い `PreparedStatement#setObject` を選択可能にする

---

src/main/java/org/seasar/doma/jdbc/dialect/Db2Dialect.java
src/main/java/org/seasar/doma/jdbc/dialect/H212126Dialect.java
src/main/java/org/seasar/doma/jdbc/dialect/H2Dialect.java
src/main/java/org/seasar/doma/jdbc/dialect/HsqldbDialect.java
src/main/java/org/seasar/doma/jdbc/dialect/Mssql2008Dialect.java
src/main/java/org/seasar/doma/jdbc/dialect/MssqlDialect.java
src/main/java/org/seasar/doma/jdbc/dialect/MysqlDialect.java
src/main/java/org/seasar/doma/jdbc/dialect/OracleDialect.java
src/main/java/org/seasar/doma/jdbc/dialect/PostgresDialect.java
src/main/java/org/seasar/doma/jdbc/dialect/SqliteDialect.java

ワイルドカード文字やエスケープ文字をカスタマイズしやすくしました。

StandardExpressionFunctionsの実装クラスにpublicなコンストラクタを追加

---

src/main/java/org/seasar/doma/jdbc/type/JdbcTypes.java
src/main/java/org/seasar/doma/jdbc/type/PortableObjectType.java

`JdbcMappingVisitor#visitStringWrapper`等にて`PortableObjectType`を利用できるよう、`PortableObjectType`をジェネリクス化しました。

PortableObjectTypeをジェネリクスにして、String等をvalueTypeとして指定できるように

---

src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java
src/main/java/org/seasar/doma/internal/jdbc/sql/PreparedSqlBuilder.java
src/main/java/org/seasar/doma/internal/jdbc/sql/ScalarInOutParameter.java
src/main/java/org/seasar/doma/internal/jdbc/sql/ScalarInParameter.java
src/main/java/org/seasar/doma/internal/jdbc/sql/SqlContext.java
src/main/java/org/seasar/doma/jdbc/JdbcMappingHint.java
src/main/java/org/seasar/doma/jdbc/entity/DefaultPropertyType.java
src/main/java/org/seasar/doma/jdbc/entity/Property.java
src/main/java/org/seasar/doma/jdbc/query/AutoBatchDeleteQuery.java
src/main/java/org/seasar/doma/jdbc/query/AutoBatchInsertQuery.java
src/main/java/org/seasar/doma/jdbc/query/AutoBatchUpdateQuery.java
src/main/java/org/seasar/doma/jdbc/query/AutoDeleteQuery.java
src/main/java/org/seasar/doma/jdbc/query/AutoInsertQuery.java
src/main/java/org/seasar/doma/jdbc/query/AutoUpdateQuery.java
src/main/java/org/seasar/doma/jdbc/query/BatchUpdateQueryHelper.java
src/main/java/org/seasar/doma/jdbc/query/UpdateQueryHelper.java
src/test/java/org/seasar/doma/internal/jdbc/sql/PreparedSqlBuilderTest.java
src/test/java/org/seasar/doma/internal/jdbc/sql/ScalarInOutParameterTest.java
src/test/java/org/seasar/doma/internal/jdbc/sql/ScalarInParameterTest.java

ドメインクラスがエンティティクラスのプロパティであり、かつSQLのバインド変数にマッピングされる場合に問題が発生していました

JdbcMappingHint#getDomainClass() がドメインクラスを返さない問題を修正

---

src/main/java/org/seasar/doma/internal/jdbc/command/EntityProvider.java
src/test/java/org/seasar/doma/internal/jdbc/command/EntityProviderTest.java

UnknownColumnHandler の handle() を空実装にすると NullPointerException が発生する問題を修正

---

src/main/java/org/seasar/doma/jdbc/UniqueConstraintException.java
src/test/java/org/seasar/doma/jdbc/UniqueConstraintExceptionTest.java

`UniqueConstraintException`のコンストラクタで親コンストラクタに渡す`cause`の引数の場所が間違っていて、可変長引数の一つとして扱われていたのを修正しました。

Fix cause position in UniqueConstraintException's constructor

---

build.gradle

次の2点についてJavadoc生成オプションを追加しました。
* `String`などのクラス名からJava SE 8のJavadocへリンクする
* クラスとパッケージの使用ページを生成する
これらがあった方がJavadocを便利に使えると思っています。

リンクに関連したJavadoc生成オプションを追加しました

---

src/main/java/org/seasar/doma/jdbc/builder/SelectBuilder.java

Stream を使った際に遅延で処理しかつクローズできるようにするため。

SelectBuilder のデフォルトの FetchType を Lazy に設定

---

docs/sources/development.rst
docs/sources/getting-started.rst
docs/sources/integration-test.rst

リポジトリのURLをSSHからHTTPSに変更しました.
理由は, HTTPSにした方が利便性が上がると考えたからです.
SSHだとGitHubにアカウントが必要であり, 公開鍵の登録も必要です.
アカウントがない人や, ちょうど手元に秘密鍵がない人は今のURLではcloneできません
(私は後者でした  😅 ).

Switching remote URLs from SSH to HTTPS

---

src/main/java/org/seasar/doma/internal/apt/AbstractGeneratingProcessor.java
src/main/java/org/seasar/doma/internal/apt/AbstractProcessor.java
src/main/java/org/seasar/doma/internal/apt/DaoProcessor.java
src/main/java/org/seasar/doma/internal/apt/DomainConvertersProcessor.java
src/main/java/org/seasar/doma/internal/apt/DomainProcessor.java
src/main/java/org/seasar/doma/internal/apt/EntityProcessor.java
src/main/java/org/seasar/doma/internal/apt/ExternalDomainProcessor.java
src/main/java/org/seasar/doma/internal/apt/SingletonConfigProcessor.java
src/main/java/org/seasar/doma/internal/apt/meta/EntityMeta.java
src/main/java/org/seasar/doma/internal/apt/meta/EntityMetaFactory.java

kapt 1.0.1-2は以下の問題がある。
- 無関係な注釈プロセッサを起動する
- コンストラクトのパラメータ名を保持しない
それぞれ次のように回避した。
- Domaの注釈プロセッサでアノテーションをチェックし必要なときにのみ動作するようにした
- `@ParameterName` で指定された名前を利用するようにした

kapt 1.0.1-2の実験的なサポート

---

src/main/java/org/seasar/doma/internal/jdbc/entity/PropertyField.java
src/test/java/org/seasar/doma/internal/jdbc/entity/Life.java
src/test/java/org/seasar/doma/internal/jdbc/entity/PropertyFieldTest.java

2段階とは、親、子、孫のように3つのクラスからなる継承構造を意味します。
close #163

エンティティクラスの継承構造が2段階の場合に無限ループが発生する不具合を修正

---

src/main/java/org/seasar/doma/expr/ExpressionFunctions.java
src/main/java/org/seasar/doma/internal/expr/NullExpressionFunctions.java
src/main/java/org/seasar/doma/jdbc/dialect/StandardDialect.java
src/test/java/org/seasar/doma/jdbc/dialect/StandardDialectTest.java

組み込み関数の LocalDate, LocalDateTime 対応 をしてみました。
次の関数を追加しています。
* java.time.LocalDateTime @roundDownTimePart(java.time.LocalDateTime timestamp)
* java.time.LocalDate @roundUpTimePart(java.time.LocalDate date)
* java.time.LocalDateTime @roundUpTimePart(java.time.LocalDateTime date)
ありそうでなかったので作成してみました。

組み込み関数の LocalDate, LocalDateTime 対応

---

src/main/java/org/seasar/doma/jdbc/dialect/StandardDialect.java
src/test/java/org/seasar/doma/jdbc/dialect/StandardDialectTest.java

`StandardExpressionFunctions#escape(String text, char escapeChar)` と `StandardExpressionFunctions#escape(String text)` の実装は逆なのではないでしょうか？

StandardExpressionFunctions#escapeがescapeCharを使用していない

---

docs/sources/annotation-processing.rst
src/main/java/org/seasar/doma/internal/apt/Options.java
src/test/java/org/seasar/doma/internal/apt/dao/DaoProcessorTest.java
src/test/resources/org/seasar/doma/internal/apt/dao/DaoProcessorTest_SqlValidationSkipWhenOptionSpecifiedByConfigFile.txt
src/test/resources/sql.validation.skip.config

#190 の対応案です。
以下のように動くよう実装したつもりです。
* 注釈オプションに`doma.config.path`オプションを追加 (デフォルトは`doma.config`)
* デフォルトでは`main/resources/doma.config`に置かれた設定ファイルを読み込む
ひとまず実装だけしてみました。方向性はあっているでしょうか。
ご検討のほどよろしくお願いします。

設定ファイルから注釈処理のオプションを読み込めるように

---

docs/sources/annotation-processing.rst
docs/sources/kotlin-support.rst
src/main/java/org/seasar/doma/internal/apt/DaoProcessor.java
src/main/java/org/seasar/doma/internal/apt/DomainConvertersProcessor.java
src/main/java/org/seasar/doma/internal/apt/DomainProcessor.java
src/main/java/org/seasar/doma/internal/apt/EmbeddableProcessor.java
src/main/java/org/seasar/doma/internal/apt/EntityProcessor.java
src/main/java/org/seasar/doma/internal/apt/ExternalDomainProcessor.java
src/main/java/org/seasar/doma/internal/apt/Options.java
src/main/java/org/seasar/doma/internal/apt/SingletonConfigProcessor.java
src/main/java/org/seasar/doma/internal/apt/meta/AbstractSqlFileQueryMetaFactory.java
src/main/java/org/seasar/doma/internal/apt/meta/DaoMetaFactory.java
src/main/java/org/seasar/doma/internal/apt/util/ResourceUtil.java
src/test/java/org/seasar/doma/internal/apt/util/ResourceUtilTest.java

#177 以降Kotlin 1.0.6 で動作したが、1.1.2では次の問題が起き動作しなくなっていた。
- リソースファイルをクラスファイルの出力先にコピーしても削除されてしまい、注釈処理でSQLファイルが見つからない
- Kotlinで書いたDaoメソッドのパラメータ名が利用されずにJavaのスタブコードが生成されてしまうため、注釈処理でSQLファイルでのバインド変数チェックができない
上記の問題に対し次のように対処する。
- kaptでリソースファイルの出力先を明示的に渡せるようにする
- DaoはKotlinではなくJavaで定義したもののみをサポートする

Kotlin 1.1.2 を実験的にサポート

---

src/main/java/org/seasar/doma/jdbc/ClassHelper.java

#246 に対する修正
`classLoader.loadClass`だとClassが取得できない場合があるので、その場合は以前と同じように`Class.forName`でClassを取得するように修正しました。

ContextClassLoaderからだとClassが取得できなことがある問題を修正

---

README.md

We will develop Doma 3 again if [JEP 326: Raw String Literals](https://openjdk.java.net/jeps/326) will be included in JDK.

Remove descriptions of Doma 3.

---

src/main/java/org/seasar/doma/internal/jdbc/dialect/StandardPagingTransformer.java
src/main/java/org/seasar/doma/internal/jdbc/sql/node/ElseNode.java
src/main/java/org/seasar/doma/internal/jdbc/sql/node/ElseifNode.java
src/main/java/org/seasar/doma/internal/jdbc/sql/node/EndNode.java
src/main/java/org/seasar/doma/internal/jdbc/sql/node/ForNode.java
src/main/java/org/seasar/doma/internal/jdbc/sql/node/IfNode.java
src/test/java/org/seasar/doma/internal/jdbc/dialect/StandardPagingTransformerTest.java

We replace the aliases even if they are inside condition or loop directives.
Close #327.

Replace table aliases in the ORDER BY clause.

---

src/main/java/org/seasar/doma/internal/apt/Options.java
src/main/java/org/seasar/doma/internal/apt/generator/DaoImplGenerator.java
src/main/java/org/seasar/doma/internal/apt/processor/DaoProcessor.java
src/main/java/org/seasar/doma/internal/jdbc/dao/AbstractDao.java
src/test/java/org/seasar/doma/internal/apt/cdi/ApplicationScoped.java
src/test/java/org/seasar/doma/internal/apt/cdi/Dependent.java
src/test/java/org/seasar/doma/internal/apt/processor/dao/ApplicationScopedDao.java
src/test/java/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest.java
src/test/java/org/seasar/doma/internal/apt/processor/dao/DependentDao.java
src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_ApplicationScopedDao.txt
src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_DependentDao.txt

Quarkus needs a no-args constructor. See https://quarkus.io/blog/quarkus-dependency-injection/

Support ApplicationScoped and Dependent annotations for Quarkus.

---

src/main/java/org/seasar/doma/internal/apt/meta/id/SequenceIdGeneratorMeta.java

The schema parameter of @SequenceGenerator annotation is not used.
Catalog names are used instead of schema names.
Expect:
```sql
select nextval('catalog.schema.my_sequence');
```
Actual:
```sql
select nextval('catalog.catalog.my_sequence');
```

Fixed that schema name was not used.

---

docs/development.rst

Fixed broken link in document.
Cause was this commit: https://github.com/google/google-java-format/commit/dc8f413b1154c7c984942294ce3ddfaaf40099b3

Fix broken link in document

---

docs/kotlin-support.rst
docs/query/batch-delete.rst
docs/query/delete.rst
docs/query/insert.rst
docs/query/select.rst

- simple mistakes like typo
- Mixing Java and Kotlin styles
- `@Delete`/`@BatchDelete` returns `Result`/`BatchResult` just like INSERT and UPDATE

Fix some mistakes in document

---

docs/domain.rst
src/main/java/org/seasar/doma/experimental/DataType.java
src/main/java/org/seasar/doma/internal/apt/MoreElements.java
src/main/java/org/seasar/doma/internal/apt/annot/Annotations.java
src/main/java/org/seasar/doma/internal/apt/annot/DataTypeAnnot.java
src/main/java/org/seasar/doma/internal/apt/cttype/CtTypes.java
src/main/java/org/seasar/doma/internal/apt/meta/domain/DataTypeMeta.java
src/main/java/org/seasar/doma/internal/apt/meta/domain/DataTypeMetaFactory.java
src/main/java/org/seasar/doma/internal/apt/meta/domain/DomainMeta.java
src/main/java/org/seasar/doma/internal/apt/meta/domain/InternalDomainMeta.java
src/main/java/org/seasar/doma/internal/apt/meta/domain/InternalDomainMetaFactory.java
src/main/java/org/seasar/doma/internal/apt/processor/AbstractDomainProcessor.java
src/main/java/org/seasar/doma/internal/apt/processor/DataTypeProcessor.java
src/main/java/org/seasar/doma/internal/apt/processor/DomainProcessor.java
src/main/java/org/seasar/doma/jdbc/domain/DomainTypeFactory.java
src/main/java/org/seasar/doma/message/Message.java
src/main/resources/META-INF/services/javax.annotation.processing.Processor

The DataType annotation is an experimental feature.
You can annotate only records with this annotation.
```java
@DataType
public record Job(String value) {}
```
is equivalent to:
```java
@Domain(valueType = String.class, accessorMethod = "value")
public record Job(String value) {}
```

Add the DataType annotation

---

doma-processor/src/main/java/org/seasar/doma/internal/apt/Options.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/entity/EntityProcessorTest.java

Now, all field names of the entity types don't have any prefix.
If you want the old prefixed names, set `$` to the "doma.entity.field.prefix" option.

Change the default value of the "doma.entity.field.prefix" option.

---

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/AssociationKind.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/declaration/SelectFromDeclaration.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/EntityqlSelectStatement.java
doma-core/src/main/java/org/seasar/doma/message/Message.java
doma-core/src/test/java/org/seasar/doma/jdbc/criteria/EntityqlSelectTest.java
doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java

It is useful to build dynamic queries easily.

Allow the innerJoin and the leftJoin methods to have no condition.

---

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/SelectBuilder.java
doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java
test-criteria/src/test/java/example/NativeSqlSelectTest.java

We generate it when it is empty and the SELECT clause includes any aggregate functions.

Generate the GROUP BY clause automatically.

---

doma-processor/src/main/java/org/seasar/doma/internal/apt/MoreTypes.java

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=544288
Close #421

Reload a typeElement with its canonical name to avoid the eclipse bug.

---

docs/criteria-api.rst
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/context/Criterion.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/declaration/ComparisonDeclaration.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/declaration/HavingDeclaration.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/declaration/WhereDeclaration.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/BuilderSupport.java
doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java
test-criteria/src/test/java/example/EntityqlSelectTest.java

If the right hand operand is null, the operator is not included in the query condition.
The following two code fragments issue a same SQL statement:
```java
entityql()
.from(e)
.where(
c -> {
if (min != null) {
c.ge(e.age, min);
}
if (max != null) {
c.le(e.age, max);
}
})
.fetch();
```
```java
entityql()
.from(e)
.where(
c -> {
c.ge(e.age, min);
c.le(e.age, max);
})
.fetch();
```

Change the semantics of condition operators.

---

.github/workflows/gradle.yml

I think that string values must be escaped.

Avoid unexpected token errors.

---

doma-kotlin/src/main/kotlin/org/seasar/doma/jdbc/criteria/statement/KListable.kt

To return nullable type, use the fetchOneOrNull method instead.

Return non-nullable type from the fetchOne method

---

docs/kotlin-support.rst

Fix a broken link

---

RELEASE_OPERATIONS.md
build.gradle.kts

Use candidate version instead of explicitly specifying

---

doma-core/src/main/java/org/seasar/doma/internal/jdbc/scalar/BasicScalar.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/scalar/OptionalBasicScalar.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/scalar/OptionalDoubleScalar.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/scalar/OptionalIntScalar.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/scalar/OptionalLongScalar.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/scalar/Scalar.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/MappedResultProvider.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/BasicPropertyTypes.java
doma-core/src/main/java/org/seasar/doma/jdbc/domain/AbstractDomainType.java
doma-core/src/main/java/org/seasar/doma/jdbc/entity/DefaultPropertyType.java
doma-core/src/main/java/org/seasar/doma/jdbc/entity/Property.java
doma-core/src/test/java/org/seasar/doma/internal/jdbc/scalar/ScalarsTest.java

Fix returning wrong type for Optional properties on selecting

---

.github/workflows/ci.yml

The keyword check is now supported officially.
https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/

Remove "skip ci" check

---

doma-core/src/main/java/org/seasar/doma/jdbc/builder/DeleteBuilder.java
doma-core/src/main/java/org/seasar/doma/jdbc/builder/InsertBuilder.java
doma-core/src/main/java/org/seasar/doma/jdbc/builder/UpdateBuilder.java
doma-core/src/test/java/org/seasar/doma/jdbc/builder/DeleteBuilderTest.java
doma-core/src/test/java/org/seasar/doma/jdbc/builder/InsertBuilderTest.java
doma-core/src/test/java/org/seasar/doma/jdbc/builder/UpdateBuilderTest.java

#679
Please consider merging them if this request is not against doma's policy.

Add params and literals methods to InsertBuilder, UpdateBuilder and DeleteBuilder

---

CONTRIBUTING.md

Excuse me for bothering you with a trivial PR. 
It seemed to be a simple typo, so I hope you will consider correcting it.

Fix typo "IEDA" -> "IDEA"

---

doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/Annotations.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/generator/DaoImplGenerator.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/dao/DaoMeta.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/dao/DaoMetaFactory.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultipleAnnotateWithDao.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultipleAnnotationConfig1.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/MultipleAnnotationConfig2.java
doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_MultipleAnnotateWithDao.txt

Add support for handling multiple `@AnnotateWith`.
If I want to handle two `Config` using `Qualifier` in an application that uses 'doma-spring-boot (So if I want to handle two `DataSources`), I have to copy `ConfigAutowireable` and define the following annotation.
```java
@AnnotateWith(annotations = {
@Annotation(target = AnnotationTarget.CLASS, type = Repository.class),
@Annotation(target = AnnotationTarget.CONSTRUCTOR, type = Autowired.class),
@Annotation(target = AnnotationTarget.CONSTRUCTOR_PARAMETER, type = Qualifier.class, elements = "\"secondary\"") })
public @interface SecondaryConfigAutowireable {
}
```
When Doma is able to handle multiple `@AnnotateWith`, I only need to define the difference that uses `Qualifier`.
```java
@AnnotateWith(annotations = {
@Annotation(target = …
```

Add support for handling multiple AnnotateWith

---

docs/criteria-api.rst
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/context/InsertSettings.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/context/UpdateSettings.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/EntityqlInsertStatement.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/EntityqlUpdateStatement.java
doma-core/src/test/java/org/seasar/doma/jdbc/criteria/EntityqlInsertTest.java
doma-core/src/test/java/org/seasar/doma/jdbc/criteria/EntityqlUpdateTest.java

For example, use `settings.exclude()` to exclude properties in the UPDATE statement:
```java
Emp emp = new Emp();
emp.setId(1);
emp.setName("aaa");
emp.setAge(20);
emp.setSalary(new BigDecimal("1000"));
emp.setVersion(1);
Emp_ e = new Emp_();
Buildable<?> stmt = entityql.update(e, emp, settings -> settings.exclude(e.age, e.salary));
```

Support to include/exclude properties in the Criteria INSERT/UPDATE statements

---

docs/kotlin-support.rst

Fixed some typo in Kotlin document.
I wonder whether `@Insert` is really supported or not in Kotlin because it seems that doma-processor does not generate `insert` method implementation in `PersonDaoImpl` class.
When I cloned [kotlin-sample](https://github.com/domaframework/kotlin-sample) project and modify `PersonDao` interface to use `@Insert` annotation, ` gradlew build` failed.
```diff
diff --git a/src/main/kotlin/sample/dao/PersonDao.kt b/src/main/kotlin/sample/dao/PersonDao.kt
index 18b3215..5066b70 100644
--- a/src/main/kotlin/sample/dao/PersonDao.kt
+++ b/src/main/kotlin/sample/dao/PersonDao.kt
@@ -1,6 +1,7 @@
package sample.dao
import org.seasar.doma.Dao
+import org.seasar.doma.Insert
import org.seasar.doma.Select
import org.seasar.doma.Sql
import org.seasar.doma.jdbc.Config
@@ …
```

Fix minor Kotlin doc issue

---

settings.gradle.kts

This reverts commit 54f4de0833f5285d7c11deb1a65b56eeffd1037c.
Because CodeQL currently supports versions below 1.7.30.

Revert "Update org.jetbrains.kotlin to v1.8.0"

---

doma-core/src/main/java/org/seasar/doma/message/Message.java

hello,
I found there is a full-width space in DOMA error message.
I think this should be half-width, so I modified it.

Replaced full-width space with half-width space

---

doma-core/src/main/java/org/seasar/doma/message/Message.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/domain/ExternalDomainMetaFactory.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/domain/BasicTypeConverter.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/domain/ExternalDomainProcessorTest.java

This pull request prohibits, for example, the following class:
```java
@ExternalDomain
public class BooleanConverter implements DomainConverter<Boolean, Integer> {
@Override
public Integer fromDomainToValue(Boolean domain) {
return domain ? 1 : 0;
}
@Override
public Boolean fromValueToDomain(Integer value) {
return value == 1;
}
}
```
This is because the Boolean type is a basic type.
See also #933.

Prohibit to treat a basic type as an external domain type

---

doma-processor/src/module/org.seasar.doma.processor/module-info.java

This fix will allow the annotation processor to run in a modular build environment.
Maven nor Gradle support this currently but it is supported by javac:
https://docs.oracle.com/en/java/javase/17/docs/specs/man/javac.html#option-processor-module-path

Fix #983 provides processor missing for apt module

---

doma-processor/build.gradle.kts

This feature is optional.
To use the shadowed jar, use the `all` classifier in the dependency notation:
```
dependencies {
annotationProcessor("org.seasar.doma:doma-processor:2.54.1:all")
}
```

Provide shadowed doma-processor jar

---

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/AggregateFunction.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/ArithmeticExpression.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/StringExpression.java
doma-core/src/test/java/org/seasar/doma/jdbc/criteria/expression/ExpressionsTest.java

In the Criteria API, we have fixed the issue where different expressions were mistakenly regarded as having the same value.

Fix expression equality in the Criteria API

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/release.yml

Because actions variables are not passed to workflows that are triggered by a pull request from a fork.

Use env context instead of vars context

---

doma-processor/src/main/java/org/seasar/doma/internal/apt/MoreElements.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/MoreTypes.java

In Eclipse, using annotation processing with Java 9 or higher leads to poorer performance. This pull request is aimed at avoiding this performance degradation.

Improve the performance of annotation processing in Eclipse

---

doma-core/src/main/java/org/seasar/doma/message/Message.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/domain/ExternalDomainMetaFactory.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/domain/Color.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/domain/ColorConverter.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/domain/ExternalDomainProcessorTest.java
doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/domain/ExternalDomainProcessorTest_ColorConverter.txt

Allowed Enum types as the first type argument in DomainConverter.

Fix an issue with the incorrect validation of the first type argument in DomainConverter

---

doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/entity/EntityPropertyNameCollector.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/entity/ImmutableUser.java
doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/entity/EntityProcessorTest_ImmutableUser.txt

#1046
An error occurs if primitive is included.
```java
@Entity
public record EmployeeEntity(
@Id long id, Address address){}
```
```
/Users/yutasaito/dev/oss/doma/test/doma-batch-include-embeddable/src/main/java/com/example/domabatchincludeembeddable/EmployeeDao.java:16: エラー: [DOMA4016] An unexpected error has occurred. It may be a bug in the Doma framework. Report the following stacktrace: java.lang.AssertionError: Null.
public interface EmployeeDao {
at org.seasar.doma.internal.util.AssertionUtil.assertNotNull(AssertionUtil.java:15)
at org.seasar.doma.internal.apt.annot.Annotations.newEmbeddableAnnot(Annotations.java:166)
at org.seasar.doma.internal.apt.meta.entity.EntityPropertyNameCollector.collectNames(EntityPropertyNameCollector.java:38)
at …
```

Fix: An error occurs if primitive is included (#1048)

---

doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlParser.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlTokenType.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlTokenizer.java
doma-core/src/main/java/org/seasar/doma/message/Message.java
doma-core/src/test/java/org/seasar/doma/internal/jdbc/sql/SqlParserTest.java
doma-core/src/test/java/org/seasar/doma/internal/jdbc/sql/SqlTokenizerTest.java

Parser-level block comments are block comments that are removed from SQL templates by Doma during parsing. These block comments are expressed in the format `/*%! ... */`.
**SQL template:**
```sql
select /*%! comment */a from b
```
**Parsed SQL:**
```sql
select a from b
```

Introduce parser-level block comments

---

integration-test-java/src/test/java/org/seasar/doma/it/other/ArrayTest.java

This PR removes a duplicate entry of `Dbms.MYSQL8` in the `@Run` annotation of the `ArrayTest` class. 
The duplicate entry does not affect the functionality of the test, but it may cause confusion for developers reading the code. This change will make the code cleaner and easier to understand.

Removed duplicate Dbms.MYSQL8 entry in ArrayTest

---

doma-processor/src/main/java/org/seasar/doma/internal/apt/MoreElements.java

To speed up annotation processing with Eclipse JDT, cache all TypeElement instances without any omissions.
This PR further improves upon #1034.

Cache all TypeElement instances in Annotation Processing

---

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java
doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/expression/KExpressions.kt

This Pull Request refactors #1102.

Refactor UserDefinedExpression and related classes

---

doma-core/src/main/java/org/seasar/doma/jdbc/tx/LocalTransaction.java

We use `ThreadLocal.remove()` to prevent memory leaks.

Fix a potential memory leak in LocalTransaction

---

doma-core/src/main/java/org/seasar/doma/jdbc/tx/LocalTransaction.java

We use `ThreadLocal.remove()` instead of `ThreadLocal.set(null)` to prevent memory leaks.
This PR is related to #1120

Fix a potential memory leak in the suspend method of LocalTransaction

---

.github/workflows/ci.yml
.github/workflows/gradle-wrapper-validation.yml

We followed the two documents below:
- https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle
- https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlewrapper-validation-action-has-been-replaced-by-gradleactionswrapper-validation

Resolve warnings in GitHub Action workflows

---

doma-core/src/main/java/org/seasar/doma/jdbc/tx/LocalTransaction.java
doma-core/src/main/java/org/seasar/doma/jdbc/tx/LocalTransactionConnection.java
doma-core/src/test/java/org/seasar/doma/jdbc/tx/KeepAliveLocalTransactionTest.java
doma-core/src/test/java/org/seasar/doma/jdbc/tx/LocalTransactionTest.java

This PR reduces the possibility of pinning in AWS RDS Proxy.
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/rds-proxy-managing.html#rds-proxy-pinning

Reduced unnecessary calls to Connection#setTransactionIsolation(level) in LocalTransaction

---

doma-core/src/main/java/org/seasar/doma/jdbc/tx/LocalTransactionDataSource.java
doma-core/src/test/java/org/seasar/doma/jdbc/tx/LocalTransactionDataSourceTest.java
integration-test-common/src/main/java/org/seasar/doma/it/IntegrationTestEnvironment.java

This pull request changes the behavior when obtaining a Connection without starting a local transaction.
Previously, an exception was thrown, but with this pull request, a Connection in auto-commit mode will be returned.

Return a Connection instead of throwing an exception when no transaction exists

---

doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlParser.java
doma-core/src/main/java/org/seasar/doma/jdbc/AbstractSqlFileRepository.java
doma-core/src/main/java/org/seasar/doma/jdbc/GreedyCacheSqlFileRepository.java
doma-core/src/main/java/org/seasar/doma/jdbc/NoCacheSqlFileRepository.java
doma-core/src/main/java/org/seasar/doma/jdbc/SqlParserConfig.java
doma-core/src/test/java/org/seasar/doma/internal/jdbc/sql/SqlParserTest.java
integration-test-common/src/main/java/org/seasar/doma/it/AppConfig.java
integration-test-common/src/main/java/org/seasar/doma/it/LineCommentRemovalSqlParserConfig.java
integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/EmployeeDao/selectById.sql

We offer an option to remove block comments and line comments from SQL templates.
Which comments to delete will be indicated in the implementation class of `SqlParserConfig`:
```java
public class LineCommentRemovalSqlParserConfig implements SqlParserConfig {
@Override
public boolean shouldRemoveBlockComment(String comment) {
return false;
}
@Override
public boolean shouldRemoveLineComment(String comment) {
return true;
}
}
```
Pass an instance of the above class to the constructor of the implementation class of `SqlFileRepository`:
```java
public class AppConfig implements Config {
...
private final SqlFileRepository sqlFileRepository =
new GreedyCacheSqlFileRepository(new LineCommentRemovalSqlParserConfig());
@Override
public SqlFileRepository getSqlFileRepository() {
return …
```

Enable removal of comments from SQL templates

---

doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KEntityql.kt
doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KNativeSql.kt

Until now, runtime error when Bellow code.
You can catch the following error at compile time with this pull request.
```
val nullableEmp : Emp? = null
val stmt = entityql.update(e, nullableEmp).execute()
```
I fixed only KEntityql and KNativeSql, but maybe other doma-kotlin code requires review.

Prevent unintentionally nullable values in doma-kotlin.

---

doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/declaration/KSetDeclaration.kt

I want to avoid nullable value when no-nullable column. Therefore using type-cast. but occurs a problem.
```kotlin
// type-cast on Kotlin(nullable) -> ok
value(e.employeeName as PropertyMetamodel<String?>, null as String?)
// type-cast on Kotlin(non-null) -> should be compile-error, but it no error occurs.
value(e.employeeName as PropertyMetamodel<String>, null as String?)
// as it is -> ok
value(e.employeeName, null as String?)
```
Removing the nullable will resolve the issue.

Improving KSetDeclaration

---

doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/expression/KExpressions.kt
doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlSelectTest.kt

Remove redundant nullables in KExpressions.
`concat` Expression arguments were required not-null.
https://github.com/domaframework/doma/blob/c8833a93cef4dbde6a81bc35426a3a5b5a8214c6/doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java#L202-L205
`min` Expression arguments were required not-null.
https://github.com/domaframework/doma/blob/c8833a93cef4dbde6a81bc35426a3a5b5a8214c6/doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java#L270-L272
`sum` Expression arguments were required not-null.
https://github.com/domaframework/doma/blob/c8833a93cef4dbde6a81bc35426a3a5b5a8214c6/doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java#L276-L278

Improving KExpressions

---

doma-core/src/main/java/org/seasar/doma/MultiInsert.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/EntityqlMultiInsertStatement.java
doma-core/src/main/java/org/seasar/doma/jdbc/dialect/H2UpsertAssembler.java
doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MssqlUpsertAssembler.java
doma-core/src/main/java/org/seasar/doma/jdbc/dialect/MysqlUpsertAssembler.java
doma-core/src/main/java/org/seasar/doma/jdbc/dialect/OracleUpsertAssembler.java
doma-core/src/main/java/org/seasar/doma/jdbc/dialect/PostgreSqlUpsertAssembler.java
doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoMultiInsertQuery.java
doma-core/src/main/java/org/seasar/doma/jdbc/query/QueryOperandPairList.java
doma-core/src/main/java/org/seasar/doma/jdbc/query/QueryRows.java
doma-core/src/main/java/org/seasar/doma/jdbc/query/UpsertAssemblerContext.java
doma-core/src/main/java/org/seasar/doma/jdbc/query/UpsertAssemblerContextBuilder.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/MultiInsertAnnot.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/generator/DaoImplQueryMethodGenerator.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoMultiInsertQueryMeta.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoMultiInsertQueryMetaFactory.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/AutoMultiInsertDao.java
doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_AutoMultiInsertDao.txt
integration-test-java/src/main/java/org/seasar/doma/it/dao/CompKeyDeptDao.java
integration-test-java/src/main/java/org/seasar/doma/it/dao/DeptDao.java
integration-test-java/src/test/java/org/seasar/doma/it/auto/AutoMultiInsertTest.java
integration-test-java/src/test/java/org/seasar/doma/it/criteria/EntityqlMultiInsertTest.java

I will enable passing DuplicateKeyType when using MultiInsert.
I am modifying the UpsertAssembler to accept multiple values.
I could not implement upsert for SQL Server, Oracle, and H2 due to lack of knowledge. Therefore, I am throwing an exception in UpsertAssembler when multiple values are received.

Add DuplicateKeyType to MultiInsert

---

doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/statement/KEntityqlMultiInsertStatement.kt
doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KEntityqlInsertMultiTest.kt

you can use onDuplicateKeyUpdate and onDuplicateKeyIgnore of insertMulti on doma-kotlin.
```kotlin
val stmt = entityql.insertMulti(e, items).onDuplicateKeyUpdate()
val stmt = entityql.insertMulti(e, items).onDuplicateKeyIgnore()
```

Support upsert with insertMulti in doma-kotlin

---

doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/declaration/KJoinDeclaration.kt

cannot set null to `eqOrIsNull` and `neOrIsNotNull` methods by 2.62.0.
sorry, I fixed.

Fix KJoinDeclaration

---

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlUpsertOnDuplicateKeyIgnoreSelectingKeys.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlUpsertOnDuplicateKeyUpdateSelectingKeys.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlUpsertOnDuplicateKeyUpdateSelectingSet.java
integration-test-java/src/test/java/org/seasar/doma/it/criteria/NativeSqlInsertTest.java

The `ClassCastException` occurred when executing `peek` after calling `onDuplicateKeyUpdate` or `onDuplicateKeyIgnore`. For example, the `ClassCastException` occurred in the following code:
```java
var nativeSql = new NativeSql(config);
var d = new Department_();
nativeSql
.insert(d)
.values(
c -> {
c.value(d.departmentId, 1);
c.value(d.departmentNo, 60);
c.value(d.departmentName, "DEVELOPMENT");
c.value(d.location, "KYOTO");
c.value(d.version, 2);
})
.onDuplicateKeyUpdate()
.peek(System.out::println)
.execute();
```

Fix an issue where calling `peek` on `NativeSql` caused a `ClassCastException`

---

gradle.properties
integration-test-java/src/test/resources/container-license-acceptance.txt
integration-test-kotlin/src/test/resources/container-license-acceptance.txt

It seems that the Docker image of Microsoft SQL Server 2019-CU12-ubuntu-20.04 does not work on Ubuntu 22.04.5. Therefore, we have upgraded the version to 2019-CU28-ubuntu-20.04.

Update SQL Server docker image to 2019-CU28-ubuntu-20.04

---

build.gradle.kts

The default value for Spotless' `lineEndings` property is `PLATFORM_NATIVE`. 
As a result, when building in a Windows environment, all line endings are converted from the currently used LF to CRLF. 
This causes a large number of change diffs to appear, significantly reducing work efficiency. 
To address this issue, we've fixed the line endings to LF even in Windows environments.
This change ensures consistent line endings across different operating systems, preventing unnecessary diffs and maintaining productivity when working on Windows machines.

Restrict Spotless line endings to LF

---

doma-core/src/main/java/org/seasar/doma/internal/jdbc/scalar/Scalars.java
integration-test-java/src/main/java/org/seasar/doma/it/criteria/Avenue.java
integration-test-java/src/main/java/org/seasar/doma/it/criteria/Place.java
integration-test-java/src/test/java/org/seasar/doma/it/criteria/QueryDslEntityqlSelectTest.java

This pull request prevents the issue causing the DOMA1007 error.
Close #1216.

Fix issue causing error when using classes annotated with `DataType` in Criteria API

---

doma-core/src/main/java/org/seasar/doma/wrapper/BigDecimalWrapper.java
doma-core/src/main/java/org/seasar/doma/wrapper/BigIntegerWrapper.java
doma-core/src/main/java/org/seasar/doma/wrapper/ByteWrapper.java
doma-core/src/main/java/org/seasar/doma/wrapper/DoubleWrapper.java
doma-core/src/main/java/org/seasar/doma/wrapper/FloatWrapper.java
doma-core/src/main/java/org/seasar/doma/wrapper/IntegerWrapper.java
doma-core/src/main/java/org/seasar/doma/wrapper/LongWrapper.java
doma-core/src/main/java/org/seasar/doma/wrapper/ShortWrapper.java
doma-core/src/test/java/org/seasar/doma/wrapper/BigDecimalWrapperTest.java
doma-core/src/test/java/org/seasar/doma/wrapper/BigIntegerWrapperTest.java
doma-core/src/test/java/org/seasar/doma/wrapper/ByteWrapperTest.java
doma-core/src/test/java/org/seasar/doma/wrapper/DoubleWrapperTest.java
doma-core/src/test/java/org/seasar/doma/wrapper/FloatWrapperTest.java
doma-core/src/test/java/org/seasar/doma/wrapper/IntegerWrapperTest.java
doma-core/src/test/java/org/seasar/doma/wrapper/LongWrapperTest.java
doma-core/src/test/java/org/seasar/doma/wrapper/ShortWrapperTest.java

This pull request removes the potential for a NullPointerException when setting numeric types for entity properties. However, there is no actual logic in Doma's code that would cause a NullPointerException in this context.

Remove potential for NullPointerException

---

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/QueryDsl.java

I added a convenient method that can be used when implementing default methods in a Dao interface using QueryDsl.
Currently, it is implemented as follows:
```java
default Employee select(Long id) {
var emp = new Employee_();
return new QueryDsl(Config.get(this)).from(emp ).where(c -> c.eq(emp.id, id)).fetchOne();
}
```
With the addition of this method, it can be simplified as follows:
```java
default Employee select(Long id) {
var emp = new Employee_();
return QueryDsl.of(this).from(emp).where(c -> c.eq(emp.id, id)).fetchOne();
}
```

add convenient factory method to QueryDsl

---

doma-core/src/main/java/org/seasar/doma/message/Message.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/Options.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/AbstractProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/DaoProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/DataTypeProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/DomainConvertersProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/DomainProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/EmbeddableProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/EntityProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/ExternalDomainProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/processor/ScopeProcessor.java

This pull request introduces a new annotation processing option, `doma.trace`, to output the execution time of annotation processing.  
To enable the `doma.trace` option, configure your build script as follows:
**Gradle**
```kotlin
tasks {
compileJava {
options.compilerArgs.addAll(listOf("-Adoma.trace=true"))
}
}
```
**Maven**
```xml
<compilerArgs>
<arg>-Adoma.dao.trace=true</arg>
</compilerArgs>
```
When the option is enabled, you will get output similar to the following:
```
75. INFO: [DOMA4463] {"execTimeMillis": 114, "processor": "org.seasar.doma.internal.apt.processor.DaoProcessor", "element": "org.seasar.doma.it.dao.CompKeyDepartmentDao"}
76. INFO: [DOMA4463] {"execTimeMillis": 20, "processor": "org.seasar.doma.internal.apt.processor.DaoProcessor", "element": …
```

Add the `doma.trace` option

---

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/declaration/ComparisonDeclaration.java
doma-core/src/test/java/org/seasar/doma/jdbc/criteria/QueryDslSqlSelectTest.java

This PR adds Iterable support for IN and NOT IN clauses in the Unified Criteria API's WHERE clause. 
For backward compatibility, existing List parameters have been kept as is.
Note: When using SQL files, Iterable parameters are already supported in Dao method arguments.

Add java.lang.Iterable support for IN and NOT IN clauses in DSL

---

doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/CallableSqlBuilder.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/PreparedSqlBuilder.java
doma-core/src/main/java/org/seasar/doma/jdbc/SqlLogFormattingVisitor.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/BuilderSupport.java
doma-core/src/main/java/org/seasar/doma/jdbc/dialect/StandardDialect.java

- Implemented a check to handle null JdbcMappingHint in visitObjectWrapper method to prevent NullPointerExceptions.
- Updated SQL log formatting to pass JdbcMappingHint for more detailed context in parameter evaluation and maintained backward compatibility with existing functionality.

Handle null JdbcMappingHint gracefully and improve SQL log formatting

---

build.gradle.kts

Update the code formatting to replace `indentWithSpaces` with `leadingTabsToSpaces` as `indentWithSpaces` has been deprecated since Spotless 7.0.0.

Use `leadingTabsToSpaces` instead of `indentWithSpaces`

---

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/AssociateCommand.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/CacheKey.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/EntityKey.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/EntityPoolIterationHandler.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/EntityPoolProvider.java
doma-core/src/main/java/org/seasar/doma/jdbc/criteria/metamodel/EntityTypeProxy.java
integration-test-java/src/test/java/org/seasar/doma/it/criteria/QueryDslEntitySelectTest.java

This pull request addressed issue causing the same entity to be generated as multiple instances within a self-referential association.
This issue occurred when writing the following code using the Criteria API:
```java
Employee_ e = new Employee_();
Employee_ m = new Employee_();
QueryDsl queryDsl = new QueryDsl(config);
List<Employee> employees =
queryDsl
.from(e)
.leftJoin(m, on -> on.eq(e.managerId, m.employeeId))
.orderBy(c -> c.asc(e.employeeId))
.associate(e, m, Employee::setManager)
.fetch();
```

Fix self-referential association duplication issue

---

doma-core/src/main/java/org/seasar/doma/jdbc/SimpleConfig.java
doma-core/src/main/java/org/seasar/doma/jdbc/SimpleConfigBuilder.java
doma-core/src/test/java/org/seasar/doma/jdbc/SimpleConfigBuilderImplTest.java
doma-core/src/test/java/org/seasar/doma/jdbc/SimpleConfigImplTest.java
doma-core/src/test/java/org/seasar/doma/jdbc/SimpleConfigTest.java
integration-test-common/src/main/java/org/seasar/doma/it/IntegrationTestEnvironment.java

Introduce `SimpleConfig` to streamline the creation of `Config` instances.
Here is an example;
```java
Config config = SimpleConfig.builder("jdbc:h2:mem:tutorial;DB_CLOSE_DELAY=-1", "sa", null)
.jdbcLogger(new Slf4jJdbcLogger())
.naming(Naming.SNAKE_UPPER_CASE)
.build();
```

Add `SimpleConfig` to simplify the construction of `Config`

---

doma-core/src/main/java/org/seasar/doma/message/Message.java

**Description:**
Updated the error message for DOMA4096 to provide additional guidance by suggesting the use of `@Association` or `@Transient` if applicable.

Enhance error message for unsupported persistent type

---

.github/workflows/codeql-analysis.yml
.github/workflows/release-draft.yml
.github/workflows/release.yml
build.gradle.kts

This pull request improves workflow maintainability and facilitates releases.

Refactor GitHub Actions workflows

---

doma-core/src/main/java/org/seasar/doma/Delete.java

Simplifies the `@Delete` annotation by removing an unused `@EntityField` annotation. No functional changes are introduced, ensuring cleaner and more maintainable code.

Remove unnecessary `@EntityField` annotation from `@Delete` annotation

---

doma-core/src/main/java/org/seasar/doma/internal/expr/node/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/expr/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/expr/util/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/command/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/dao/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/dialect/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/entity/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/scalar/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/node/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/jdbc/util/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/util/package-info.java
doma-core/src/main/java/org/seasar/doma/internal/wrapper/package-info.java
doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/package-info.java
doma-core/src/main/java/org/seasar/doma/jdbc/statistic/package-info.java
doma-core/src/main/java/org/seasar/doma/util/package-info.java

This pull request adds `package-info.java` files across various packages to enhance clarity and provide documentation. These files serve as a central location for package-level JavaDoc, improving maintainability and understanding of the codebase.
No new functionality is introduced, and existing code behavior remains unchanged.

Add package-info.java for documentation clarity

---

doma-processor/src/main/java/org/seasar/doma/internal/apt/DomaProcessor.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/Options.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/ProcessingContext.java
doma-processor/src/main/java/org/seasar/doma/internal/apt/Resources.java
doma-processor/src/main/resources/META-INF/gradle/incremental.annotation.processors
doma-processor/src/test/java/org/seasar/doma/internal/apt/AptinaTestCase.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/aggregate/AggregateStrategyProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/aggregate/AggregateStrategyTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/experimental/SqlTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/domain/DomainConvertersProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/domain/DomainProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/domain/ExternalDomainProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/embeddable/EmbeddableProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/entity/EntityProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/entity/association/EntityProcessorTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/metamodel/MetamodelOptionTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/metamodel/MetamodelTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/metamodel/ScopeTest.java
doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/scope/ScopeProcessorTest.java
gradle/libs.versions.toml
integration-test-java-common/build.gradle.kts
integration-test-java/build.gradle.kts

- Fixed incorrect configuration for Gradle's incremental annotation processing.
- Updated Doma Compile plugin to version 4.0.0, including configuration to read resource files from SOURCE_PATH.
- Added an integration test option to the Doma processor.

Fix Gradle annotation processing configuration and update Doma plugin

---

.github/workflows/codeql-analysis.yml

Added `--no-daemon` and `--no-build-cache` options to the Gradle command in the CodeQL workflow for a clean and isolated build environment, improving reliability and consistency during analysis.

Enhance Gradle build configuration in CodeQL workflow

---

gradle/libs.versions.toml

This reverts commit fb96449d2c34105d46526604de539ba8085f35ed.
Since `google-java-format` v1.29.0 doesn’t support JDK 17, we’ll use v1.28.0 instead.

Revert "fix(deps): update dependency com.google.googlejavaformat:google-java-format to v1.29.0 (#1446)"
