src/main/java/org/seasar/doma/message/Message.java
#77 の問題への対策です。
なんらかの理由でメッセージの取得に失敗した場合は、できる限り詳細な情報を含め本来のメッセージと同等の情報量を保持します。
=> リソースバンドルが取得できない場合はデフォルトのリソースバンドルにフォールバックする

src/main/java/org/seasar/doma/internal/apt/BatchSqlValidator.java, src/main/java/org/seasar/doma/internal/apt/ExpressionValidator.java, src/main/java/org/seasar/doma/internal/apt/SqlValidator.java, src/main/java/org/seasar/doma/internal/apt/meta/AbstractQueryMeta.java, src/main/java/org/seasar/doma/internal/apt/meta/AbstractSqlFileQueryMetaFactory.java, src/main/java/org/seasar/doma/internal/apt/meta/SqlFileBatchModifyQueryMetaFactory.java, src/test/java/org/seasar/doma/internal/apt/AptTestCase.java, src/test/java/org/seasar/doma/internal/apt/dao/BatchSqlValidatorTest.java, src/test/java/org/seasar/doma/internal/apt/dao/DaoProcessorTest.java, src/test/java/org/seasar/doma/internal/apt/dao/Issue82Dao.java, src/test/java/org/seasar/doma/internal/apt/dao/SqlValidatorTest.java, src/test/resources/META-INF/org/seasar/doma/internal/apt/dao/Issue82Dao/update.sql, src/test/resources/org/seasar/doma/internal/apt/dao/DaoProcessorTest_Issue82.txt
更新カラムリスト生成コメント `/*%populate*/`  を使ったメソッドで DOMA4122 エラーが出る問題を修正しました。
fix #82
=> populate を使ったメソッドで DOMA4122 が出る‏問題を修正

src/main/java/org/seasar/doma/jdbc/AbstractJdbcLogger.java, src/main/java/org/seasar/doma/jdbc/JdbcLogger.java, src/main/java/org/seasar/doma/jdbc/tx/LocalTransaction.java
いつも大変便利に使わせて頂いております。Logger内におそらくtypoと思われる表現がありましたのでどこかのタイミングで更新頂けると幸いです。
=> Failuer -> Failure

src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java, src/main/java/org/seasar/doma/internal/jdbc/sql/PreparedSqlBuilder.java, src/main/java/org/seasar/doma/internal/jdbc/sql/SqlContext.java, src/main/java/org/seasar/doma/jdbc/JdbcMappingHint.java, src/main/java/org/seasar/doma/jdbc/entity/DefaultPropertyType.java, src/main/java/org/seasar/doma/jdbc/entity/Property.java, src/main/java/org/seasar/doma/jdbc/query/AutoBatchDeleteQuery.java, src/main/java/org/seasar/doma/jdbc/query/AutoBatchInsertQuery.java, src/main/java/org/seasar/doma/jdbc/query/AutoBatchUpdateQuery.java, src/main/java/org/seasar/doma/jdbc/query/AutoDeleteQuery.java, src/main/java/org/seasar/doma/jdbc/query/AutoInsertQuery.java, src/main/java/org/seasar/doma/jdbc/query/AutoUpdateQuery.java, src/main/java/org/seasar/doma/jdbc/query/BatchUpdateQueryHelper.java, src/main/java/org/seasar/doma/jdbc/query/UpdateQueryHelper.java, src/test/java/org/seasar/doma/internal/jdbc/sql/PreparedSqlBuilderTest.java
=> Revert "JdbcMappingHint#getDomainClass() がドメインクラスを返さない問題を修正"

src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java, src/main/java/org/seasar/doma/internal/jdbc/sql/SqlParser.java, src/main/java/org/seasar/doma/internal/jdbc/sql/node/AbstractClauseNode.java, src/main/java/org/seasar/doma/internal/jdbc/sql/node/LogicalOperatorNode.java, src/main/java/org/seasar/doma/internal/jdbc/sql/node/WordNode.java, src/test/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilderTest.java
=> 埋め込み変数コメントの展開後にスペースを挿入しない

src/main/java/org/seasar/doma/jdbc/ClassHelper.java
教えて頂いた修正で大丈夫でした。ご確認よろしくお願いします。
https://twitter.com/nakamura_to/status/690820483701288961
=> Spring Boot DevToolsに対応

src/main/java/org/seasar/doma/jdbc/builder/DeleteBuilder.java, src/main/java/org/seasar/doma/jdbc/builder/InsertBuilder.java, src/main/java/org/seasar/doma/jdbc/builder/SelectBuilder.java, src/main/java/org/seasar/doma/jdbc/builder/UpdateBuilder.java, src/main/java/org/seasar/doma/jdbc/query/AbstractSelectQuery.java, src/main/java/org/seasar/doma/jdbc/query/SqlModifyQuery.java, src/test/java/org/seasar/doma/jdbc/builder/DeleteBuilderTest.java, src/test/java/org/seasar/doma/jdbc/builder/InsertBuilderTest.java, src/test/java/org/seasar/doma/jdbc/builder/SelectBuilderTest.java, src/test/java/org/seasar/doma/jdbc/builder/UpdateBuilderTest.java
=> クエリビルダのgetSql()の呼び出しでエラーが発生しないように修正

docs/sources/query/select.rst, src/main/java/org/seasar/doma/internal/apt/DaoGenerator.java, src/main/java/org/seasar/doma/internal/apt/meta/QueryReturnMeta.java, src/main/java/org/seasar/doma/internal/apt/meta/SqlFileSelectQueryMeta.java, src/main/java/org/seasar/doma/internal/apt/meta/SqlFileSelectQueryMetaFactory.java, src/main/java/org/seasar/doma/jdbc/builder/SelectBuilder.java, src/main/java/org/seasar/doma/jdbc/command/SelectCommand.java, src/main/java/org/seasar/doma/jdbc/query/AbstractSelectQuery.java, src/main/java/org/seasar/doma/jdbc/query/SelectQuery.java, src/main/java/org/seasar/doma/message/Message.java, src/test/java/org/seasar/doma/internal/apt/dao/DaoProcessorTest.java, src/test/java/org/seasar/doma/internal/apt/dao/ResultStreamDao.java, src/test/java/org/seasar/doma/internal/jdbc/command/EntityProviderTest.java, src/test/java/org/seasar/doma/internal/jdbc/command/ScalarProviderTest.java, src/test/java/org/seasar/doma/jdbc/command/SelectCommandTest.java, src/test/resources/META-INF/org/seasar/doma/internal/apt/dao/ResultStreamDao/select.sql, src/test/resources/META-INF/org/seasar/doma/internal/apt/dao/ResultStreamDao/selectById.sql, src/test/resources/META-INF/org/seasar/doma/internal/apt/dao/ResultStreamDao/selectByIdAndName.sql, src/test/resources/META-INF/org/seasar/doma/internal/apt/dao/ResultStreamDao/selectByIdAsMap.sql, src/test/resources/META-INF/org/seasar/doma/jdbc/command/SelectCommandTest/testExecute_resultStream.sql, src/test/resources/org/seasar/doma/internal/apt/dao/DaoProcessorTest_ResultStream.txt
=> 検索用メソッドの戻り値の型を Stream とすることを認めた

docs/sources/query-builder/index.rst, src/main/java/org/seasar/doma/jdbc/builder/BuildingHelper.java, src/main/java/org/seasar/doma/jdbc/builder/DeleteBuilder.java, src/main/java/org/seasar/doma/jdbc/builder/InsertBuilder.java, src/main/java/org/seasar/doma/jdbc/builder/Param.java, src/main/java/org/seasar/doma/jdbc/builder/SelectBuilder.java, src/main/java/org/seasar/doma/jdbc/builder/UpdateBuilder.java, src/test/java/org/seasar/doma/jdbc/builder/DeleteBuilderTest.java, src/test/java/org/seasar/doma/jdbc/builder/InsertBuilderTest.java, src/test/java/org/seasar/doma/jdbc/builder/SelectBuilderTest.java, src/test/java/org/seasar/doma/jdbc/builder/UpdateBuilderTest.java
=> クエリビルダでリテラルの埋め込みをサポート

src/main/java/org/seasar/doma/jdbc/GreedyCacheSqlFileRepository.java, src/main/java/org/seasar/doma/jdbc/SqlFileRepository.java, src/test/java/org/seasar/doma/jdbc/GreedyCacheSqlFileRepositoryTest.java
enkan などでリフレクションを使わずキャッシュを削除するため
https://github.com/kawasima/enkan/blob/4dca6922267434a923596e43e3a5dba2f35f7968/enkan-component-doma2/src/main/java/enkan/component/doma2/DomaProvider.java#L60
=> SQLファイルのキャッシュを削除するためのメソッドを追加

src/main/java/org/seasar/doma/jdbc/builder/MapInsertBuilder.java, src/test/java/org/seasar/doma/jdbc/builder/MapInsertBuilderTest.java
再度のPull Request失礼します。
#173 の修正版として、Builder版を作成しました。
問題なければ反映をお願いします。
`MapBatchInsertBuilder`については追って作成致します。
=> Mapをパラメータとして自動でInsert文を組み立てるMapInsertBuilderを追加

src/main/java/org/seasar/doma/internal/apt/meta/DaoMetaFactory.java, src/main/java/org/seasar/doma/message/Message.java, src/test/java/org/seasar/doma/internal/apt/dao/DaoProcessorTest.java, src/test/java/org/seasar/doma/internal/apt/dao/MultiDaoExtendsDao.java, src/test/java/org/seasar/doma/internal/apt/dao/MyDao.java, src/test/java/org/seasar/doma/internal/apt/dao/MyDao2.java, src/test/java/org/seasar/doma/internal/apt/dao/NotOnlyDefaultMethodsChild.java, src/test/java/org/seasar/doma/internal/apt/dao/NotOnlyDefaultMethodsExtendsDao.java, src/test/java/org/seasar/doma/internal/apt/dao/NotOnlyDefaultMethodsParent.java, src/test/java/org/seasar/doma/internal/apt/dao/OnlyDefaultMethods.java, src/test/java/org/seasar/doma/internal/apt/dao/OnlyDefaultMethodsExtendsDao.java, src/test/resources/org/seasar/doma/internal/apt/dao/DaoProcessorTest_NonDaoExtends.txt, src/test/resources/org/seasar/doma/internal/apt/dao/DaoProcessorTest_OnlyDefaultMethodsExtends.txt
=> Dao インタフェースがデフォルトメソッドのみが定義されたインタフェースを継承可能に変更

docs/sources/query-builder/index.rst, src/main/java/org/seasar/doma/jdbc/builder/SelectBuilder.java, src/test/java/org/seasar/doma/jdbc/builder/SelectBuilderTest.java
いずれもIN句のリストを組み立てるために使われることを想定したメソッドです。
=> SelectBuilder に params メソッドと literals メソッドを追加

src/main/java/org/seasar/doma/jdbc/dialect/OracleDialect.java, src/test/java/org/seasar/doma/jdbc/dialect/Oracle11DialectTest.java, src/test/java/org/seasar/doma/jdbc/dialect/OracleDialectTest.java
https://gitter.im/domaframework/doma?at=59bc6677bac826f054c29036
=> Remove full-width `％` and `＿` from wild cards in Oracle dialect

docs/sources/query/delete.rst
replace `includeVersion` to `ignoreVersion`.
=> Fix a wrong annotation parameter in a Docs example.

docs/sources/expression.rst, src/main/java/org/seasar/doma/expr/ExpressionFunctions.java, src/main/java/org/seasar/doma/internal/expr/NullExpressionFunctions.java, src/main/java/org/seasar/doma/jdbc/dialect/StandardDialect.java
https://twitter.com/nakamura_to/status/926699547715289088
=> Use `CharSequence` as parameter in expression functions

src/main/java/org/seasar/doma/jdbc/tx/LocalTransaction.java, src/main/java/org/seasar/doma/jdbc/tx/LocalTransactionContext.java, src/test/java/org/seasar/doma/jdbc/tx/LocalTransactionContextTest.java
=> Fix broken local transaction

docs/query/insert.rst
I finished translating query/insert.rst.
=> Translate query insert

docs/query/update.rst
I finished translating query/update.rst.
=> Translate 'query/update.rst'

docs/expression.rst
Finished translating expression.rst.
=> Translate expression.rst

docs/transaction.rst
=> Translate transaction.rst

docs/query/select.rst
I finished translating query/select.rst.
=> Finished translating 'query/select.rst'

docs/sources/query/batch-update.rst, docs/sources/query/update.rst
=> 更新(excludeNull)、バッチ更新(include,exclud)の説明を修正

docs/query/batch-update.rst
I finished translating query/batch-update.rst.
=> Finished translating 'query/batch-update.rst'

docs/getting-started-eclipse.rst
I finished translating getting-started-eclipse.rst.
=> Finished translating 'getting-started-eclipse.rst'

docs/query/batch-update.rst
When I translated query/bacth-update.rst, I mistook translating return value type.
I corrected the wrong type.
Sorry to my mistake.
=> Corrected the wrong type.

README.md
=> Put example code in README.md

src/main/java/org/seasar/doma/internal/apt/Types.java, src/main/java/org/seasar/doma/internal/apt/cttype/AbstractCtType.java, src/main/java/org/seasar/doma/internal/apt/cttype/ArrayCtType.java, src/main/java/org/seasar/doma/internal/apt/cttype/CtType.java, src/main/java/org/seasar/doma/internal/apt/cttype/CtTypeVisitor.java, src/main/java/org/seasar/doma/internal/apt/cttype/CtTypes.java, src/main/java/org/seasar/doma/internal/apt/cttype/SimpleCtTypeVisitor.java, src/main/java/org/seasar/doma/internal/apt/generator/DaoImplMethodGenerator.java, src/main/java/org/seasar/doma/internal/apt/meta/query/QueryParameterMeta.java, src/main/java/org/seasar/doma/internal/apt/validator/SqlValidator.java, src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java, src/main/java/org/seasar/doma/message/Message.java, src/test/java/org/seasar/doma/internal/apt/processor/dao/SqlValidationDao.java, src/test/java/org/seasar/doma/internal/apt/processor/dao/SqlValidatorTest.java, src/test/java/org/seasar/doma/internal/jdbc/sql/SqlParserTest.java
=> support Array Object in %for clause

README.md
=> Clarify license and copyright

docs/query/batch-delete.rst
I finished translating query/batch-delete.rst.
=> Finished translating 'query/batch-delete.rst'

docs/domain.rst, docs/embeddable.rst, docs/entity.rst, src/main/java/org/seasar/doma/Entity.java, src/main/java/org/seasar/doma/internal/apt/cttype/CtTypes.java, src/main/java/org/seasar/doma/internal/apt/meta/domain/DomainMetaFactory.java, src/main/java/org/seasar/doma/internal/apt/meta/entity/EmbeddableMetaFactory.java, src/main/java/org/seasar/doma/internal/apt/meta/entity/EntityMetaFactory.java, src/main/java/org/seasar/doma/internal/apt/util/ElementKindUtil.java, src/main/java/org/seasar/doma/message/Message.java, src/test/java/org/seasar/doma/internal/apt/util/ElementKindUtilTest.java
We support [Records](https://openjdk.java.net/jeps/359).
Examples:
```java
@Entity
public record Employee(
@Id Integer id, 
Address address, 
Job job, 
@Version Integer version) {
}
```
```java
@Embeddable
public record Address(String city, String street) {}
```
```java
@Domain(valueType = String.class, accessorMethod = "value")
public record Job(String value) {}
```
=> Support records

docs/kotlin-support.rst, docs/sql.rst, doma-core/src/main/java/org/seasar/doma/Sql.java, doma-core/src/main/java/org/seasar/doma/jdbc/AbstractSqlFileRepository.java, doma-core/src/main/java/org/seasar/doma/jdbc/SqlFileRepository.java, doma-core/src/main/java/org/seasar/doma/jdbc/query/SqlFileScriptQuery.java, doma-core/src/test/java/org/seasar/doma/jdbc/AbstractSqlFileRepositoryTest.java, doma-core/src/test/java/org/seasar/doma/jdbc/query/SqlFileScriptQueryTest.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/Annotations.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/experimental/AnnotationConflictDao.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/experimental/BatchModifySqlFileElementConflictDao.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/experimental/DefaultMethodConflictDao.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/experimental/ModifySqlFileElementConflictDao.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/experimental/SqlAnnotationDao.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/experimental/SqlTest.java
The word "experimental" has been removed from the package name.
=> Support the Sql annotation officially.

doma-processor/src/main/java/org/seasar/doma/internal/apt/Options.java
#385  was not enought to change the default value.
=> Fix the default value of the "doma.entity.field.prefix" option

doma-processor/src/main/java/org/seasar/doma/internal/apt/Options.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/entity/EntityProcessorTest.java
Revert #389 and #385.
We don't need these changes.
=> Revert the commits related to the default value of the prefix

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/declaration/SelectFromDeclaration.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/EntityqlSelectStatement.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlSelectStarting.java, doma-core/src/test/java/org/seasar/doma/jdbc/criteria/EntityqlSelectTest.java, doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java
It is useful to build dynamic queries easily.
=> Make the limit and offset values nullable.

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/ForUpdateOption.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/context/ForUpdate.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/declaration/SelectFromDeclaration.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/SelectBuilder.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/EntityqlSelectStatement.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/statement/NativeSqlSelectStarting.java, doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java
It is useful to build dynamic queries easily.
=> Add the ForUpdateOption enum.

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/StringExpression.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/BuilderSupport.java, doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java
- lower
- upper
- trim
- ltrim
- rtrim
=> Add some string expressions:

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/AggregateFunction.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/BasicPropertyTypes.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/LiteralExpression.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/BuilderSupport.java, doma-core/src/test/java/org/seasar/doma/jdbc/criteria/expression/ExpressionsTest.java, test-criteria/src/test/java/example/NativeSqlSelectTest.java
- Byte
- Boolean
- BigDecimal
- BigInteger
- Double
- Float
- LocalDate
- LocalDateTime
- LocalTime
- Long
- Short
=> Support the literal expression for the following data types:

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/BuilderSupport.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/UpdateBuilder.java, doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlUpdateTest.java
=> Fix invalid update statement.

build.gradle.kts
Remove warning messages and polish code.
=> Refactor build.gradle.kts

README.md
=> Add a description for Kotlin projects

README.md
=> Format example code in README.md

README.md
=> Support Java 15

RELEASE_OPERATIONS.md
=> Clean RELEASE_OPERATIONS.md

.github/workflows/changelog.yml
Specify the branch name to the ref parameter
[skip ci]
=> Fix changelog.yml

docs/slf4j-support.rst
=> Use "runtimeOnly" dependency for logback

RELEASE_OPERATIONS.md
=> Get releaseVersion by GitHub CLI

RELEASE_OPERATIONS.md
=> Add a link to the doma-slf4j repository

docs/config.rst, docs/transaction.rst, doma-core/src/main/java/org/seasar/doma/jdbc/tx/KeepAliveLocalTransaction.java, doma-core/src/main/java/org/seasar/doma/jdbc/tx/LocalTransaction.java
=> Rename AppConfig to DbConfig

README.md, build.gradle.kts
=> Fix version property name

README.md
=> Switch from Gitter to Zulip

doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlParser.java, doma-core/src/test/java/org/seasar/doma/internal/jdbc/sql/SqlParserTest.java
=> Retain first semi-colon instead of removing it in SQL template

README.md
=> Replace doma-quarkus with quarkiverse-doma

RELEASE_OPERATIONS.md
=> Fix markdown syntax

README.md
=> Support Java 16

.github/workflows/changelog.yml, build.gradle.kts
=> Pass parameters using environment variables

settings.gradle.kts
This reverts commit 38220ee6c626aaeedd1f008977589dfbf4e1ef8a.
=> Revert "Update org.jetbrains.kotlin to v1.8.10"

integration-test-common/build.gradle.kts, integration-test-java-additional/build.gradle.kts, integration-test-java/build.gradle.kts, integration-test-kotlin/build.gradle.kts
See https://docs.gradle.org/8.0.1/userguide/java_plugin.html#sec:incremental_compile
=> Disable incremental compilation after a failure

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/release.yml
Reverts domaframework/doma#990
=> Revert "Update gradle/gradle-build-action action to v2.9.0"

doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoBatchDeleteQuery.java, doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoBatchInsertQuery.java, doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoBatchModifyQuery.java, doma-core/src/main/java/org/seasar/doma/jdbc/query/AutoBatchUpdateQuery.java, integration-test-java/src/main/java/org/seasar/doma/it/entity/IdColumnOnlyEmployee.java, integration-test-java/src/test/java/org/seasar/doma/it/criteria/EntityqlBatchUpdateTest.java, integration-test-java/src/test/java/org/seasar/doma/it/criteria/EntityqlUpdateTest.java
I am currently getting the following error with AutoBatchUpdateQuery when empty update columns.
I fixed it for that.
```
org.seasar.doma.jdbc.JdbcException: [DOMA2016] Cannot get java.sql.PreparedStatement.
PATH=[null].
SQL=[update EMPLOYEE se where EMPLOYEE_ID = ? and EMPLOYEE_NO = ? and EMPLOYEE_NAME = ? and MANAGER_ID = ? and HIREDATE = ? and SALARY = ? and DEPARTMENT_ID = ? and ADDRESS_ID = ? and VERSION = ?].
The cause is as follows: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "UPDATE EMPLOYEE SE WHERE[*] EMPLOYEE_ID = ? AND EMPLOYEE_NO = ? AND EMPLOYEE_NAME = ? AND MANAGER_ID = ? AND HIREDATE = ? AND SALARY = ? AND DEPARTMENT_ID = ? AND ADDRESS_ID = ? AND VERSION = ?"; expected "SET"; SQL statement:
update EMPLOYEE se where EMPLOYEE_ID = ? and EMPLOYEE_NO …
```
=>  Fixed a bug that occurred when the update columns was empty in AutoBatchUpdateQuery

doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/Annotations.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/entity/EntityPropertyNameCollector.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/dao/IncludeAndExcludeDao.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/entity/_ImmutableUser.java, doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/dao/DaoProcessorTest_IncludeAndExcludeDao.txt, integration-test-java/src/main/java/org/seasar/doma/it/dao/StaffDao.java, integration-test-java/src/test/java/org/seasar/doma/it/auto/AutoUpdateTest.java
=> Make it possible to include or exclude embedded properties

doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KEntityql.kt, doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KNativeSql.kt, doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KEntityqlSelectTest.kt, doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlSelectTest.kt
Support subQuery(#1030)  for KEntityql and KNativeSql
=> Support subQuery in for KEntityql and KNativeSql

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/AliasExpression.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/BuilderSupport.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/SelectBuilder.java, integration-test-java/src/main/java/org/seasar/doma/it/criteria/Salary.java, integration-test-java/src/test/java/org/seasar/doma/it/criteria/EntityqlSelectTest.java, integration-test-java/src/test/java/org/seasar/doma/it/criteria/NativeSqlSelectTest.java
- Add comment on usage
- Fix AliasExpression#asClass
- Add AliasExpression to Expressions
- Can specify alias on orderBy
=> Improving AliasExpression

doma-core/src/main/java/org/seasar/doma/internal/jdbc/dialect/Mssql2008PagingTransformer.java, doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/NodePreparedSqlBuilder.java, doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SimpleSqlNodeVisitor.java, doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlParser.java, doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlTokenType.java, doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/SqlTokenizer.java, doma-core/src/main/java/org/seasar/doma/internal/jdbc/sql/node/DistinctNode.java, doma-core/src/main/java/org/seasar/doma/jdbc/SqlNodeVisitor.java, doma-core/src/test/java/org/seasar/doma/internal/jdbc/dialect/Mssql2008PagingTransformerTest.java, integration-test-java/src/main/java/org/seasar/doma/it/dao/EmployeeDao.java, integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/EmployeeDao/selectDistinctAll.sql, integration-test-java/src/test/java/org/seasar/doma/it/sqlfile/SqlFileSelectPagingTest.java
=> Insert the TOP clause in the correct position

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/Expressions.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/expression/UserDefinedExpression.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/query/BuilderSupport.java, doma-core/src/test/java/org/seasar/doma/jdbc/criteria/NativeSqlSelectTest.java, doma-core/src/test/java/org/seasar/doma/jdbc/criteria/expression/ExpressionsTest.java, doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/expression/KExpressions.kt, doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlSelectTest.kt, integration-test-java/src/test/java/org/seasar/doma/it/criteria/CustomExpressions.java, integration-test-java/src/test/java/org/seasar/doma/it/criteria/NativeSqlSelectTest.java, integration-test-java/src/test/java/org/seasar/doma/it/criteria/NativeSqlUpdateTest.java
You can define your own Expression.
For example, users can implement count-distinct with multiple columns, etc.
=> Create UserDefinedExpression feature

doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/declaration/KJoinDeclaration.kt, doma-kotlin/src/test/kotlin/org/seasar/doma/jdbc/criteria/KNativeSqlSelectTest.kt
Improving KJoinDeclaration.
Add shortage methods to KJoinDeclaration.
=> Improving KJoinDeclaration

doma-core/src/main/java/org/seasar/doma/jdbc/tx/LocalTransaction.java
=> Minimize the calls to Connection#setTransactionIsolation(level) in LocalTransaction

doma-kotlin/src/main/kotlin/org/seasar/doma/kotlin/jdbc/criteria/KEntityql.kt
related to https://github.com/domaframework/doma/pull/1141
=> Prevent unintentionally nullable values in KEntityql#insertMulti

integration-test-common/src/main/java/org/seasar/doma/it/LogConfigurator.java
This issue was introduced in https://github.com/domaframework/doma/pull/1159.
=> Fix issue with duplicate log output in the integration test projects

build.gradle.kts
Remove descriptions related to the previously deleted unit-test module.
=> Remove unused code from build script

build.gradle.kts, doma-kotlin/build.gradle.kts, doma-processor/build.gradle.kts, doma-slf4j/build.gradle.kts, gradle/libs.versions.toml, integration-test-common/build.gradle.kts, integration-test-kotlin/build.gradle.kts, settings.gradle.kts
See https://docs.gradle.org/8.10.2/userguide/platforms.html
=> Manage library versions in libs.versions.toml

build.gradle.kts, settings.gradle.kts
This PR changes the build.gradle.kts and settings.gradle.kts files to improve readability and maintainability.
=> Improve build scripts

doma-core/src/test/java/org/seasar/doma/jdbc/criteria/QueryDslEntityqlSelectTest.java
=> Renaming to QueryDslEntityqlSelectTest

doma-core/src/main/java/org/seasar/doma/jdbc/criteria/QueryDsl.java
This PR introduces a very minor change.
=> Add an import statement for a class referenced by the Javadoc `@link` tag

.github/workflows/ci.yml, README.md, doma-core/src/main/java/org/seasar/doma/internal/Artifact.java, gradle.properties
Since we don't want to execute signing, we will use test tasks instead of build tasks.
=> Fix Gradle tasks in the ecj job

README.md
=> Update Compatibility matrix

README.md
Update README.md by adding a new "Supported by" section to acknowledge our supporters. Make sure to reorganize and relocate the existing Backers section accordingly.
=> Add "Supported by" section to README

doma-core/src/main/java/org/seasar/doma/jdbc/EntityId.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AggregateCommand.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationEntityKey.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationEntityPool.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationEntityPoolEntry.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationEntityPoolIterationHandler.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationEntityPoolProvider.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationLinkerType.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationPathKey.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/AssociateCommand.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/EntityKey.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/EntityPoolIterationHandler.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/EntityPoolProvider.java, integration-test-java/src/main/java/org/seasar/doma/it/dao/EmployeeDao.java, integration-test-java/src/main/java/org/seasar/doma/it/dao/ImmutableEmpDao.java, integration-test-java/src/main/java/org/seasar/doma/it/entity/ImmutableDept.java, integration-test-java/src/main/java/org/seasar/doma/it/entity/ImmutableEmp.java, integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/EmployeeDao/selectByIdWithManager.sql, integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/ImmutableEmpDao/selectById.sql, integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/ImmutableEmpDao/selectByIds.sql, integration-test-java/src/test/java/org/seasar/doma/it/aggregate/AggregateTest.java
Refactor entity association and caching logic for improved performance and maintainability. No functional changes.
=> Refactor entity association and caching logic

doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AbstractAggregateStrategyType.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AggregateStrategyType.java, doma-core/src/main/java/org/seasar/doma/jdbc/query/AbstractSelectQuery.java, doma-core/src/main/java/org/seasar/doma/message/Message.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/generator/AggregateStrategyTypeGenerator.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/aggregate/AggregateStrategyMeta.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/aggregate/AggregateStrategyMetaFactory.java, doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/aggregate/AggregateStrategyProcessorTest_ChildEntityStrategy.txt, doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/aggregate/AggregateStrategyProcessorTest_DeptStrategy.txt, doma-processor/src/test/resources/org/seasar/doma/internal/apt/processor/aggregate/AggregateStrategyProcessorTest_EmpStrategy.txt, integration-test-java/src/main/java/org/seasar/doma/it/dao/DepartmentDao.java, integration-test-java/src/main/resources/META-INF/org/seasar/doma/it/dao/DepartmentDao/illegalAlias.sql, integration-test-java/src/test/java/org/seasar/doma/it/aggregate/AggregateTest.java
This pull request enhances aggregate strategies by adding alias validation to ensure data integrity and accuracy in the aggregation process.
=> Enhance aggregate strategies with alias validation

doma-core/src/main/java/org/seasar/doma/jdbc/EntityRef.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AggregateCommand.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationEntityPoolIterationHandler.java, doma-core/src/main/java/org/seasar/doma/jdbc/aggregate/AssociationEntityPoolProvider.java, doma-core/src/main/java/org/seasar/doma/jdbc/criteria/command/AssociateCommand.java
**Description:**
The pull request includes updates to switch from direct entity object usage to `EntityRef` for improved encapsulation and entity management. Relevant classes and methods have been modified to ensure consistency across the codebase.
=> Switch to `EntityRef` for improved entity handling

doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/entity/EntityMetaFactory.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/entity/association/EntityProcessorTest.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/entity/association/IllegalAssociation.java
This reverts commit 9e058d3e4595913a2ebaebcb73df088ca4703361, reversing changes made to 0acb4bb38e3727292007eef3c157f88e111c977e.
=> Revert "Remove invalid association handling and related tests (#1285)"

doma-processor/src/main/java/org/seasar/doma/internal/apt/DomaProcessor.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/ProcessingContext.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/RoundContext.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/Annotations.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/cttype/CtTypes.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/TestProcessor.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/MyAnnotationProcessor.java
This pull request enhances the code by adding non-null checks to constructor arguments and refactoring RoundContext to prevent 'this' reference leakage.
=> Refactor RoundContext

doma-core/src/main/java/org/seasar/doma/jdbc/SimpleConfig.java, doma-core/src/main/java/org/seasar/doma/jdbc/SimpleConfigBuilder.java, doma-core/src/test/java/org/seasar/doma/jdbc/SimpleConfigBuilderImplTest.java, doma-core/src/test/java/org/seasar/doma/jdbc/SimpleConfigImplTest.java
Modify the SimpleConfig implementation to include a unique dataSourceName.
=> Add unique dataSourceName to SimpleConfig implementation

.sdkmanrc
Updated the development JDK to version 17.0.14-tem. This change may affect local development environments, so please ensure your JDK is updated accordingly.
=> Update JDK version for development environment

doma-core/src/main/java/org/seasar/doma/message/Message.java
- Corrected grammar mistakes in various error messages.
- Enhanced clarity by rephrasing certain error descriptions for better user understanding.
=> Fix grammar and improve clarity in error messages

doma-core/src/main/java/org/seasar/doma/jdbc/CommandImplementors.java, doma-core/src/main/java/org/seasar/doma/jdbc/Config.java, doma-core/src/main/java/org/seasar/doma/jdbc/ConfigProvider.java, doma-core/src/main/java/org/seasar/doma/jdbc/ConfigSupport.java, doma-core/src/main/java/org/seasar/doma/jdbc/DuplicateColumnHandler.java, doma-core/src/main/java/org/seasar/doma/jdbc/JdbcException.java, doma-core/src/main/java/org/seasar/doma/jdbc/QueryImplementors.java, doma-core/src/main/java/org/seasar/doma/jdbc/ScriptFileLoader.java, doma-core/src/main/java/org/seasar/doma/jdbc/UnknownColumnHandler.java
This pull request focuses on improving the Javadoc comments in the `org.seasar.doma.jdbc` package to enhance code readability and maintainability. 
No functional changes have been made to the code; all updates pertain solely to documentation improvements.
=> Improve Javadoc for org.seasar.doma.jdbc package

doma-core/src/main/java/org/seasar/doma/jdbc/dialect/Dialect.java
Updated Javadoc comments in the `org.seasar.doma.jdbc.dialect` package to improve clarity and accuracy.
No functional changes were made; this update only enhances documentation.
=> Improve Javadoc in `org.seasar.doma.jdbc.dialect` package

doma-processor/src/main/java/org/seasar/doma/internal/apt/DomaProcessor.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/cttype/CtTypes.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/dao/DaoMetaFactory.java
This pull request introduces code refactoring to enhance clarity and maintainability in the following areas:
- Simplified processor instantiation within `DomaProcessor`.
- Streamlined function list initialization in `CtTypes`.
- Updated `DaoMetaFactory` to use `QueryMetaFactorySupplier`.
These changes are focused on improving the codebase without altering functionality.
=> Refactor processor and factory initialization for clarity

.sdkmanrc, doma-processor/src/main/java/org/seasar/doma/internal/apt/DomaProcessor.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/ProcessingContext.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/RoundContext.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/TestProcessor.java, doma-processor/src/test/java/org/seasar/doma/internal/apt/processor/MyAnnotationProcessor.java
Refactored the annotation processing workflow for improved clarity and efficiency.
=> Refactor annotation processing

README.md
This pull request adds a badge for DeepWiki to the README file.
=> Add DeepWiki badge to README  

doma-core/src/main/java/org/seasar/doma/NClobFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/Annotations.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/annot/MultiInsertAnnot.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/dao/DaoMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/ArrayCreateQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoBatchModifyQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoFunctionQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoModifyQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoMultiInsertQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/AutoProcedureQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/BlobCreateQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/ClobCreateQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/DefaultQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/NClobCreateQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/QueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/SQLXMLCreateQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/SqlFileBatchModifyQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/SqlFileModifyQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/SqlFileScriptQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/SqlFileSelectQueryMetaFactory.java, doma-processor/src/main/java/org/seasar/doma/internal/apt/meta/query/SqlProcessorQueryMetaFactory.java
- **Changes Introduced**:
- Add Javadoc comments for better documentation of annotation factory methods.
- Optimize DAO method processing to enhance performance.
=> Optimize annotation processing and improve performance
